CREATE TABLE LOGIN (
	id INTEGER NOT NULL,
	usuario VARCHAR(16) NOT NULL,
	senha VARCHAR(16) NOT NULL,

	CONSTRAINT PK_LOGIN PRIMARY KEY(id),
	CONSTRAINT UN_LOGIN_USUARIO UNIQUE(usuario)
);

CREATE TABLE ALUNO (
	id INTEGER NOT NULL,
	nome VARCHAR(64) NOT NULL,
	rg VARCHAR(16) NOT NULL,
	cpf VARCHAR(16) NOT NULL,
	email VARCHAR(64),
	telefone VARCHAR(16),
	status VARCHAR(16),
	ra INTEGER NOT NULL,
	logradouro VARCHAR(64),
	numero INTEGER,
	cep VARCHAR(16),
	bairro VARCHAR(32),
	cidade VARCHAR(32),
	estado VARCHAR(2),

	CONSTRAINT PK_ALUNO PRIMARY KEY(id),
	CONSTRAINT UN_ALUNO_CPF UNIQUE(cpf),
	CONSTRAINT UN_ALUNO_RA UNIQUE(ra) 
);

CREATE TABLE LIVRO (
	id INTEGER NOT NULL,
	nome VARCHAR(64) NOT NULL,
	autor VARCHAR(64) NOT NULL,
	publicacao DATETIME  NOT NULL,
	editora VARCHAR(64) NOT NULL,
	nro_edicao INTEGER NOT NULL,
	isbn VARCHAR(32) NOT NULL,
	situacao VARCHAR(16) NOT NULL,

	CONSTRAINT PK_LIVRO PRIMARY KEY(id)
);

CREATE TABLE RESERVA (
	id INTEGER NOT NULL,
	id_livro INTEGER NOT NULL,
	id_aluno INTEGER NOT NULL,
	data_retirada DATETIME,
	data_devolucao DATETIME,
	tipo VARCHAR(16) NOT NULL,
	ativo INTEGER NOT NULL,

	CONSTRAINT PK_RESERVA PRIMARY KEY(id),
	CONSTRAINT FK_RESERVA_LIVRO FOREIGN KEY(id_livro) REFERENCES LIVRO(id),
	CONSTRAINT FK_RESERVA_ALUNO FOREIGN KEY(id_aluno) REFERENCES ALUNO(id)
);

INSERT INTO Login (id, usuario, senha) VALUES (1, 'admin', '1234');